[versions]
buildKonfig = "0.15.0"
kotlin = "1.9.21"
kotlinx-coroutines = "1.7.3"
kotlinx-datetime = "0.4.1"
kotlinx-serialization = "1.6.1"
arrow = "1.2.3"
uuid = "0.8.2"
diglolCrypto = "0.1.5"
diglolEncoding = "0.3.0"
kodein = "7.21.2"
touchlab-kermit = "2.0.3"
ktor = "2.3.9"
logback = "1.4.11"
npm-htmlParser = "6.1.11"
npm-express = "4.18.2"
npm-firebase-admin = "11.11.1"
npm-google-firestore = "6.8.0"
npm-google-pubsub = "4.0.7"

[libraries]
buildKonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
#noinspection UnusedVersionCatalogEntry
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
diglol-crypto = { module = "com.diglol.crypto:mac", version.ref = "diglolCrypto" }
diglol-encoding = { module = "com.diglol.encoding:encoding", version.ref = "diglolEncoding" }
kodein = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "touchlab-kermit" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
npm-htmlParser = { group = "npm", name = "node-html-parser", version.ref = "npm-htmlParser" }
npm-express = { group = "npm", name = "express", version.ref = "npm-express" }
npm-firebase-admin = { group = "npm", name = "firebase-admin", version.ref = "npm-firebase-admin" }
npm-google-firestore = { group = "npm", name = "@google-cloud/firestore", version.ref = "npm-google-firestore" }
npm-google-pubsub = { group = "npm", name = "@google-cloud/pubsub", version.ref = "npm-google-pubsub" }

# Dependencies of the included gradle-plugins
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]

# Plugins defined by this project
# TODO: Figure out how to do the below for multi-project setup
thecodinglove-base-node = { id = "base-node-plugin", version = "unspecified" }
thecodinglove-base-browser = { id = "base-browser-plugin", version = "unspecified" }
thecodinglove-node-module = { id = "node-module-plugin", version = "unspecified" }
thecodinglove-build-config = { id = "build-config-plugin", version = "unspecified" }
thecodinglove-browser-binary = { id = "browser-binary-plugin", version = "unspecified" }
thecodinglove-node-binary = { id = "node-binary-plugin", version = "unspecified" }